### ISSUE TITLE
create data repo on Nextcloud

### ISSUE THREAD

**Issue by matthiasdemuzere** [FPS-URB-RCC/CORDEX-CORE-WG#2]
Goal: centralize all data in one space.

Note that not all data will be hosted here, eg. the CORDEX-CORE output that is stored in [ESGF](https://cordex.org/data-access/esgf/)

**Comment by jesusff** [comment]
Hi both, sorry for the delay. Thank you both!

@matthiasdemuzere, I will fix the paths to point to the new location. This data space seems public, right? I should be able to sync it to my computer using a nextcloud client. I'll need to figure it out. There seems to be a way to [add it to our nextcloud server](https://docs.nextcloud.com/server/latest/user_manual/en/files/federated_cloud_sharing.html).

@GLangendijk, yes, orog files for RegCM are available [from ESGF](https://esgf-data.dkrz.de/search/cordex-dkrz/?offset=0&limit=10&type=Dataset&replica=false&latest=true&domain=AFR-22%2CCAM-22%2CCAS-22%2CEAS-22%2CEUR-11%2CNAM-22%2CSAM-22%2CSEA-22%2CWAS-22&experiment=evaluation&rcm_name=RegCM4%2CRegCM4-0%2CRegCM4-2%2CRegCM4-4%2CRegCM4-6%2CRegCM4-7&variable=orog&project=CORDEX&project=CORDEX-Adjust&project=CORDEX-Reklies&project=CORDEX-ESD&facets=rcm_name%2Cproject%2Cproduct%2Cdomain%2Cinstitute%2Cdriving_model%2Cexperiment%2Cexperiment_family%2Censemble%2Crcm_version%2Ctime_frequency%2Cvariable%2Cvariable_long_name%2Ccf_standard_name%2Cdata_node). Also the [land-sea masks](https://esgf-data.dkrz.de/search/cordex-dkrz/?offset=0&limit=10&type=Dataset&replica=false&latest=true&domain=AFR-22%2CCAM-22%2CCAS-22%2CEAS-22%2CEUR-11%2CNAM-22%2CSAM-22%2CSEA-22%2CWAS-22&experiment=evaluation&rcm_name=RegCM4%2CRegCM4-0%2CRegCM4-2%2CRegCM4-4%2CRegCM4-6%2CRegCM4-7&variable=sftlf&project=CORDEX&project=CORDEX-Adjust&project=CORDEX-Reklies&project=CORDEX-ESD&facets=rcm_name%2Cproject%2Cproduct%2Cdomain%2Cinstitute%2Cdriving_model%2Cexperiment%2Cexperiment_family%2Censemble%2Crcm_version%2Ctime_frequency%2Cvariable%2Cvariable_long_name%2Ccf_standard_name%2Cdata_node). Definitely, we could use them to exclude water bodies in the definition of rural surroundings for the urban centers.
