### ISSUE TITLE
Common color scale for urban fraction

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/CORDEX-CORE-WG#23]
@yaizaquintana, please, we need to revert this to a fixed value ([before](https://github.com/FPS-URB-RCC/CORDEX-CORE-WG/blob/b58350d769d06a93ffdbd03dca49eb784f74618c/uhi/urban_areas.py#L511C62-L511C72), it was `vmax_urb  = 0.6`)

https://github.com/FPS-URB-RCC/CORDEX-CORE-WG/blob/76804d058e5c174d085e8d4b66c6533f926d6966/uhi/urban_areas.py#L544

and regenerate all figures. Otherwise, we cannot compare sfturf across models or cities

**Comment by yaizaquintana** [comment]
the change has been reverted to a fixed value with vmax_urb = 0.6
