### ISSUE TITLE
REMO urban fraction data misaligned

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/CORDEX-CORE-WG#24]
_From @JavierDiezSierra (Copied over from off-topic thread)_

The urban fraction file for the EUR-11 and REMO model has different geographic coordinates than the "orog" file available on the ESGF. Additionally, longitudes for the urban fraction goes from 0 to 360.

In the results shown below, the longitude for the urban fraction has been converted to -180 to 180.

![comparo_jj](https://github.com/user-attachments/assets/affaebbc-fc4b-44e5-a4b0-879d701e19ae)

@jesusff

**Comment by JavierDiezSierra** [comment]
The difference in coordinates came from an old issue. It has now been fixed, and Jonny has already provided us the new file.
