### ISSUE TITLE
sample script to reproject regular lat lon (or other) to the rotated CORDEX grids

### ISSUE THREAD

**Issue by matthiasdemuzere** [FPS-URB-RCC/CORDEX-CORE-WG#3]

**Comment by jesusff** [comment]
I don't remember why this was necessary. Maybe to regrid regular observational grids to the RCM grids? Misaligned UF rotated grids for a given model are being handled separately by requesting them to the provider (see #8 )

I close this one for the moment. Please, reopen it, if there was a clear usage plan for these scripts.
