### ISSUE TITLE
Initiate github project

### ISSUE THREAD

**Issue by matthiasdemuzere** [FPS-URB-RCC/CORDEX-CORE-WG#5]
Goal: Initiate a github project to:

- structure to do's => small tasks!
- indicate who is responsible
- provide status
- provide platform to discuss progress or provide support when help is needed.

For now this project is private, I just invite the people that were already part of the github repository.
This means that the general public can not see what is written in these issues, see example below when I am logged out:

![Image](https://user-images.githubusercontent.com/6926916/213005704-e5c9c265-8997-424c-97eb-e41caaf4b8c6.png)

Of course, the Issue section itself is still public, so anyone can still create Issues outside of this Project framework.
Please let me know if you want to change this behaviour ...

**Comment by GLangendijk** [comment]
Very good!
